#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_CARD                                101
#define IDD_WAIT                                102
#define IDD_CREDITS1                            103
#define IDD_CREDITS2                            104
#define IDD_CLOSEDIALOG                         105
#define IDD_TOOMANYSESSIONS                     106
#define IDR_POPUPMENU                           106
#define IDD_NEWPASS_DIALOG                      108
#define IDI_ICON2								110
#define IDI_ICONGRAY							111
#define IDI_LIFERING                            120
#define IDC_CONTADOR                            1000
#define IDC_HOST                                1001
#define IDC_TEXT                                1001
#define IDC_CLOSE_REMOTE                        1002
#define IDC_TARGETA                             1002
#define IDC_CELLA                               1003
#define IDC_WAITBUTTON                          1003
#define IDC_VALOR                               1004
#define IDC_BITMAP                              1005
#define IDC_QUESTIO                             1006
#define IDD_LOGINDIALOG                         1007
#define IDC_USER                                1008
#define IDC_PASSWORD                            1009
#define IDC_REPEATPASSWORD                      1010
#define IDC_REASON                              1011
#define IDM_ENABLE_ESSO                         40001
#define IDM_DISABLE_ESSO                        40002
#define IDM_UPDATE                              40003
#define IDM_LOGIN                               40006
#define IDM_LOGOFF                              40007
#define IDM_USER_ESSO                           40008
#define IDM_USER_NEW_DESKTOP                    40009
#define IDM_OPEN_MENU                           40010
#define IDM_USER_DESKTOP                        40011
