/* List of defines generated by configure. Included with preprocessor flag,
 * -include, to avoid long list of -D defines on the compile command-line.
 * Do not edit.
 */

#ifndef _MOZILLA_CONFIG_H_
#define _MOZILLA_CONFIG_H_

#define D_INO d_ino
#define HAVE_DIRENT_H 1
#define HAVE_GETOPT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBM 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_RINT 1
#define HAVE_SNPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_STDINT_H 1
#define HAVE_STRERROR 1
#define HAVE_UINT64_T 1
#define HAVE_UNISTD_H 1
#define HAVE_VA_COPY 1
#define HAVE___CXA_DEMANGLE 1
#define HW_THREADS 1
#define IBMBIDI 1
#define JS_THREADSAFE 1
#define MMAP_MISSES_WRITES 1
#define MOZILLA_LOCALE_VERSION "1.9a1"
#define MOZILLA_REGION_VERSION "1.9a1"
#define MOZILLA_SKIN_VERSION "1.8"
#define MOZILLA_VERSION "1.9a3pre"
#define MOZILLA_VERSION_U 1.9a3pre
#define MOZ_BUILD_APP xulrunner
#define MOZ_CAIRO_GFX 1
#define MOZ_DEFAULT_TOOLKIT "cairo-windows"
#define MOZ_DISTRIBUTION_ID "org.mozilla"
#define MOZ_DLL_SUFFIX ".dll"
#define MOZ_EMBEDDING_LEVEL_BASIC 1
#define MOZ_EMBEDDING_LEVEL_DEFAULT 1
#define MOZ_EMBEDDING_LEVEL_MINIMAL 1
#define MOZ_ENABLE_CANVAS 1
#define MOZ_ENABLE_LIBXUL 1
#define MOZ_FEEDS 1
#define MOZ_JSLOADER 1
#define MOZ_LOGGING 1
#define MOZ_MATHML 1
#define MOZ_MORKREADER 1
#define MOZ_NO_XPCOM_OBSOLETE 1
#define MOZ_PLACES 1
#define MOZ_PROFILELOCKING 1
#define MOZ_RDF 1
#define MOZ_STORAGE 1
#define MOZ_SVG 1
#define MOZ_SVG_FOREIGNOBJECT 1
#define MOZ_THEBES 1
#define MOZ_UPDATE_CHANNEL default
#define MOZ_USER_DIR "Mozilla"
#define MOZ_VIEW_SOURCE 1
#define MOZ_XPINSTALL 1
#define MOZ_XTF 1
#define MOZ_XUL 1
#define MOZ_XULRUNNER 1
#define MOZ_XUL_APP 1
#define NO_X11 1
#define NO_X11 1
#define NS_PRINTING 1
#define NS_PRINT_PREVIEW 1
#define OJI 1
#define STDC_HEADERS 1
#define STDC_HEADERS 1
#define VA_COPY va_copy
#define WIN32 1
#define WIN32_LEAN_AND_MEAN 1
#define WINVER 0x501
#define XP_WIN 1
#define XP_WIN32 1
#define X_DISPLAY_MISSING 1
#define _WIN32 1
#define _WIN32_IE 0x0400
#define _WIN32_WINNT 0x501
#define _WINDOWS 1
#define _X86_ 1

#endif /* _MOZILLA_CONFIG_H_ */

